### ISSUE TITLE
RangeError: Internal error. Icu error

### ISSUE THREAD

**Issue by rzr** [isaacs/string-locale-compare#1]
hi,
I am reporting an issue here but I am not sure this is the right place (feel free to close if it's noise to you).

Others are facing similar error:

- https://github.com/search?q=%22RangeError%3A+Internal+error.+Icu+error%22&type=Issues

I faced some error in this library used  by "npm view" from Yocto's devtool, Any clue ?
here the stack trace

```
devtool add 'npm://registry.npmjs.org;package=iotjs-express;version=0.0.22'

ERROR: Bitbake Fetcher Error: FetchError('Fetch command export PSEUDO_DISABLED=1;
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/10000/bus";
export SSH_AGENT_PID="6144";
export SSH_AUTH_SOCK="/tmp/ssh-juKkYFLKlZ3S/agent.6142";
export PATH="...oniro/build-oniro-linux/tmp/sysroots-uninative/x86_64-linux/usr/bin:...oniro/oe-core/scripts:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/bin/x86_64-oniro-linux:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot/usr/bin/crossscripts:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/sbin:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/bin:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/sbin:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/bin:...oniro/bitbake/bin:...oniro/build-oniro-linux/tmp/hosttools";
export HOME="/tmp/tmpwm49pzdy"; NPM_CONFIG_GLOBALCONFIG=/dev/null NPM_CONFIG_USERCONFIG=/tmp/tmpv_80mn41
npm view iotjs-async@0.0.9 --json=true --registry=http://registry.npmjs.org/

failed with exit code 1,
output:\n...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/
work/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/@isaacs/string-locale-compare/index.js:6\n
const collator = new Collator(locale, opts)\n                   ^\n\n
RangeError: Internal error. Icu error.\n
at new Collator (<anonymous>)\n
at collatorCompare (...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/@isaacs/string-locale-compare/index.js:6:20)\n    at module.exports (...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/@isaacs/string-locale-compare/index.js:37:7)\n
at Object.<anonymous> (...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/lib/node_modules/npm/lib/utils/config/describe-all.js:2:63)\n
at Module._compile (node:internal/modules/cjs/loader:1101:14)\n
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n
at Module.load (node:internal/modules/cjs/loader:981:32)\n
at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n
at Module.require (node:internal/modules/cjs/loader:1005:19)\n
at require (node:internal/modules/cjs/helpers:102:18)\n', None)
```

Relate-to: https://icu.unicode.org/

**Comment by mukulov** [comment]
> hi,
> I am reporting an issue here but I am not sure this is the right place (feel free to close if it's noise to you).
> 
> Others are facing similar error:
> 
> - https://github.com/search?q=%22RangeError%3A+Internal+error.+Icu+error%22&type=Issues
> 
> 
> I faced some error in this library used  by "npm view" from Yocto's devtool, Any clue ?
> here the stack trace
> 
> ```
> devtool add 'npm://registry.npmjs.org;package=iotjs-express;version=0.0.22'
> 
> ERROR: Bitbake Fetcher Error: FetchError('Fetch command export PSEUDO_DISABLED=1;
> export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/10000/bus";
> export SSH_AGENT_PID="6144";
> export SSH_AUTH_SOCK="/tmp/ssh-juKkYFLKlZ3S/agent.6142";
> export PATH="...oniro/build-oniro-linux/tmp/sysroots-uninative/x86_64-linux/usr/bin:...oniro/oe-core/scripts:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/bin/x86_64-oniro-linux:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot/usr/bin/crossscripts:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/sbin:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/bin:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/sbin:...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/bin:...oniro/bitbake/bin:...oniro/build-oniro-linux/tmp/hosttools";
> export HOME="/tmp/tmpwm49pzdy"; NPM_CONFIG_GLOBALCONFIG=/dev/null NPM_CONFIG_USERCONFIG=/tmp/tmpv_80mn41
> npm view iotjs-async@0.0.9 --json=true --registry=http://registry.npmjs.org/
> 
> failed with exit code 1,
> output:\n...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/
> work/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/@isaacs/string-locale-compare/index.js:6\n
> const collator = new Collator(locale, opts)\n                   ^\n\n
> RangeError: Internal error. Icu error.\n
> at new Collator (<anonymous>)\n
> at collatorCompare (...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/@isaacs/string-locale-compare/index.js:6:20)\n    at module.exports (...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/@isaacs/string-locale-compare/index.js:37:7)\n
> at Object.<anonymous> (...oniro/build-oniro-linux/tmp/work/recipetool-olgv4tm6/work/recipe-sysroot-native/usr/lib/node_modules/npm/lib/utils/config/describe-all.js:2:63)\n
> at Module._compile (node:internal/modules/cjs/loader:1101:14)\n
> at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n
> at Module.load (node:internal/modules/cjs/loader:981:32)\n
> at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n
> at Module.require (node:internal/modules/cjs/loader:1005:19)\n
> at require (node:internal/modules/cjs/helpers:102:18)\n', None)
> ```
> 
> Relate-to: https://icu.unicode.org/

Hi, have you managed to solve this problem?
